version: "3"

services:
  # after mysql start run: mysql -h 127.0.0.1 -u root -p forgottenserver < ./schema.sql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=forgottenserver"
    healthcheck:
      test: "exit 0"

  forgottenserver:
    image: 4funio/forgottenserver
    command: [""]
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - "./data:/opt/tfs/data"
      - "./config.lua:/opt/tfs/config.lua"
    links:
      - mysql
    depends_on:
      - mysql
